// A bunch of splash messages
// All of these are jokes, and may or may not have basis in reality
// Strings must be 66 characters or shorter

pub static SPLASH_MESSAGES: &[&str] = &[
    "Don't trust everything you read!",
    "Infdev, forever!",
    "99.9% open source!",
    "Made with KiCad!",
    "Made with OpenSCAD!",
    "Made with Rust!",
    "Made with C. Sorry!",
    "Made with Raspberry Pi!",
    "Made with Sodalite!",
    "Works with Windows!",
    "Doesn't work with Mac!",
    "Works with Linux!",
    "Not USB-IF approved!",
    "DRM sucks!",
    "17776 is good!",
    "Something is terribly wrong!",
    "Fear of failure is a poor reason not to try!",
    "I hope there are beasties in the next one!",
    "Science compels us to blow up the sun!",
    "Now with Super Tetanus!",
    "Hello, Gordon!",
    "I am not a moron!",
    "Tennessee approved!",
    "Now U Know Gaming!",
    "Don't awoo! $350 penalty!",
    "14 cents! I'll take that!",
    "Shoutouts to SimpleFlips!",
    "Veni! Vidi! Vici!",
    "In your mind!",
    "The Accident!",
    "Sisyphean!",
    "Cool!",
    "Normal!",
    "Good!",
    "Cool and normal!",
    "Little Bobby Tables approved!",
    "Trans rights are human rights!",
    "Trans wrongs are human wrongs!",
    "You are valid!",
    "kd1unb4b3q4t58fwlpcbzcbnm76a8fp!",
    "kimne78kx3ncx6brgo4mv6wki5h1ko!",
    // Thanks Percy!
    "What do you mean this isn't legal?",
    "Someone stole my wallet!",
    "The voices made me do it!",
    "they won't believe you!",
    // Thanks Prismatica!
    "Also try Fate/Stay Night!",
    "Also try Witch on the Holy Night!",
    "People die when they are killed!",
    "Featuring Dante from the Devil May Cry Series!",
    "Show me your motivation!",
    "Not TezCo approved!",
    "Not legal in Commander!",
    // Thanks Basil!
    "Made from 100% recycled plastic ♹!",
    // Thanks evets!
    "Updates monthly!",
    "Updates yearly!",
    "Updates fortnightly!",
    "Updates fortnitely!",
    "I can't believe it's not butter!",
    "It was butter all along!",
    "10 GOTO 20!",
    "Playable with a standard deck of 52 cards!",
    "Send any complaints via SSB to 7.200 MHz!",
    "I II II I_ !",
    "Proudly handmade since 1926!",
    "Now in smell-o-vision!",
    "Vista-ready!",
    "More reliable than a 737 Max!",
    "Not permitted for use in nuclear reactors!",
    // TODO: "they called em lunchables because you were able to lunch or so it was implied",
    // Thanks Evergreen!
    "Runs on 110V AC! (adapter not included)",
    "IPX7 certified!",
    "Do not feed after midnight!",
    "Help, I'm trapped in a tagline factory!",
    "Puts the uke in Jukebox!",
    // Thanks aptmoo!
    "Lunch empowerment!",
    "100% AI-free!",
    "ChatGPT is M-x doctor!",
    "Eight Megs And Constantly Swapping!",
    "Memory-safe!",
    "M-x butterfly!",
    "Put your right hand into the box!",
    "Fear is the mind-killer!",
    "Walk without rhythm!",
    "And on the pedestal these words appear!",
    "A worm through time!",
    "Watch the fridge!",
    "Stretched!",
    "Show me the Champion of Light!",
    "I'll show you the Herald of Darkness!",
    "Yötôn Yõ!",
    "Knows 10,000 things!",
    "Master the elements!",
    // TODO: "Lives in a **house** on Ash Tree Lane!" (make house blue!)
    "The enemy's gate is down!",
    "Clean your room!",
    "Rotate a cow in your mind!",
    "Think big thoughts!",
    "Blinkenlights!",
    "Revealed to me in a dream!",
    "Rinsing machine!",
    "Filling machine!",
    "Wide as it is tall!",
    "The future rules!",
    "You are likely to be eaten by a Grue!",
    "Always remember how special you are!",
    "Does the black moon howl?",
    // TODO: "\"Almost Christmas\" means it wasn't Christmas!", (conditioned on the local date being 12-24)
    // (and xkcd 1774)
    "As seen on TV!",
    "Biodegradable!",
    "Gluten free!",
    "Premium!",
    "Stone-ground!",
    "Bespoke!",
    "Cage-free!",
    "Gourmet!",
    "Fire-roasted!",
    "Glazed!",
    "Flambé!",
    "Craft barrel-aged smoked!",
    "Authentic homemade!",
    "Sun-dried whole extra sharp!",
    "Organic!",
    "All-natural!",
    "Locally-sourced!",
    "Artisinal!",
    "Kosher!",
    "Grade A!",
    "Low calorie!",
    "Lite!",
    "Original flavor!",
    // Thanks marlee_goat!
    "Incredibly useful*",
    "*[citation needed]",
    "You'Re Using It!",
    // Thanks HylianMage!
    "Lunch-able!",
    "Also try One Way Ticket!",
    "Also try ChaoticStupidDnD!",
    "Nostalgia Critic approved!",
    "Do you like how I walk?",
    "Do you like how I talk?",
    "TezCo approved!",
    "Better than Hunt Down the Freeman!",
    "A spicy meatball!",
    "Also try the delicious fruit!",
    "Also try the strawberries!",
    "Ethically sourced!",
    "Now with wires!",
    "No assembly required!",
    "Cow tools!",
    "Awoooooooooooooooooo!",
    "This sentence is tautological!",
    "More juke, less box!",
    "Don't buy crypto!",
    "Updates weekly!",
    "Hexagons!",
    "Also try VodBot!",
    "Also try VOXbot!",
    "Customizable!",
    "Now with more filament!",
    "Homestuck is good, kinda!",
    ":(){ :|:& };:",
    "Baba is you!",
    "Extra buttons included!",
    "Look directly at implosions!",
    // Thanks Magic!
    "Prepare thyself!",
    "Who you were before is insignificant!",
    "Who you are now is inconcievable!",
    // Thanks lexikiq!
    "Made with blood!",
    // Thanks Skysometric!
    "Doesn't actually play music (unless you tell it to)!",
    "Duck!",
    "Goose!",
    "GUARANTEED!!!",
    "Knock knock...",
    "Paper cranes!",
    "Press F2 pay respects!",
    "Super slurp!",
    "Waking up\"; startStrings=null; bindings=null;",
];
