name: "Build desktop app"
on:
  push:
    paths:
      - "desktop/**"
      - ".github/workflows/build-desktop.yaml"

jobs:
  build-desktop-linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Get dependencies"
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          version: 1
          execute_install_scripts: true
          packages: libudev-dev libgtk-3-dev libxdo-dev libpulse-dev
      - name: "Update Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Build desktop (Linux)"
        run: cd desktop/ && cargo build --release && mv target/release/jukebox_desktop target/release/jukebox_desktop_linux
      - name: "Upload artifact (Linux)"
        uses: actions/upload-artifact@v4
        with:
          name: jb-desktop-linux
          path: desktop/target/release/jukebox_desktop_linux
          retention-days: 90

  build-desktop-windows:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Update Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Install cargo-binstall"
        uses: cargo-bins/cargo-binstall@v1.10.12
      - name: "Install cross-rs"
        run: cargo binstall cross
      - name: "Build desktop (Windows)"
        run: cd desktop/ && cross build --target x86_64-pc-windows-gnu --release && mv target/x86_64-pc-windows-gnu/release/jukebox_desktop.exe target/x86_64-pc-windows-gnu/release/jukebox_desktop_windows.exe
      - name: "Upload artifact (Windows)"
        uses: actions/upload-artifact@v4
        with:
          name: jb-desktop-windows
          path: desktop/target/x86_64-pc-windows-gnu/release/jukebox_desktop_windows.exe
          retention-days: 90
