name: "Build case models"
on:
  push:
    paths:
      - "hardware-case/**"
      - ".github/workflows/build-hardware-case.yaml"
      - "assets/textlogo.svg"

jobs:
  build-hardware-case:
    runs-on: ubuntu-latest
    steps:
      - name: "Get dependencies"
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          version: 1
          execute_install_scripts: true
          packages: openscad
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "OpenSCAD build"
        run: ./hardware-case/build.sh
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: jb-hardware-case
          path: hardware-case/build/case-*.stl
          retention-days: 90
