name: "Build firmware"
on:
  push:
    paths:
      - "firmware/**"
      - ".github/workflows/build-firmware.yaml"

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Update Rust"
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: thumbv8m.main-none-eabihf
      - name: "Get dependencies"
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          version: 1
          execute_install_scripts: true
          packages: libudev-dev
      - name: "Install flip-link"
        run: cargo install flip-link
      - name: "Install elf2uf2-rs"
        run: cargo install elf2uf2-rs
      - name: "Build binary with Cargo (Keypad)"
        run: cd firmware/ && DEFMT_LOG=off cargo build -F "keypad" --release && elf2uf2-rs target/thumbv6m-none-eabi/release/jukebox_firmware target/thumbv6m-none-eabi/release/jukebox_firmware.uf2
      - name: "Upload binary artifact (Keypad)"
        uses: actions/upload-artifact@v4
        with:
          name: jb_firmware_keypad
          path: firmware/target/thumbv6m-none-eabi/release/jukebox_firmware.uf2
          retention-days: 90
